# In this template we are going to learn about usage of parameters
# Types: string, number, list, AWS specific type
# Use of the of the intrinsic function !Ref
# Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:
  WebserverAmiid:
    Description: The EC2 AMI id
    Type: String
    Default: ami-03a6eaae9938c858c 

  WebserverInstancetype:
    Description: The EC2 Instance Type
    Type: String
    Default: t2.micro

  WebserverVolumesize:
    Description: The EC2 Volumesize
    Type: Number
    Default: 8

  AppserverAmiid:
    Description: The EC2 AMI id
    Type: String
    Default: ami-03a6eaae9938c858c

  AppserverInstancetype:
    Description: The EC2 Instance Type
    Type: String
    Default: t2.micro

  AppserverVolumesize:
    Description: The EC2 Volumesize
    Type: Number
    Default:8

  S3bucketname:
    Description: The name of the S3 bucket
    Type: String
  


Resources:
  Webserver:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref WebserverAmiid
      InstanceType: !Ref WebserverInstancetype      
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: !Ref WebserverVolumesize
  Appserver:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref AppserverAmiid
      InstanceType: !Ref AppserverInstancetype
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: !Ref AppserverVolumesize
  
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3bucketname